/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paciente;

import ConexionPaciente.buscarPaciente_Conexion;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author j3s
 */
public class buscarPacienteForm extends javax.swing.JFrame {

    /**
     * Creates new form buscarPacienteForm
     */
    
    public static String MensajeBuscarPaciente = "";
    public static String MensajeBuscarPaciente2 = "";
    public static String MensajeBuscarPaciente3 = "";
    public static String MensajeBuscarPaciente4 = "";
    public static String MensajeBuscarPaciente5 = "";
    public static String MensajeBuscarPaciente6 = "";
    public static String MensajeBuscarPaciente7 = "";
    public static String MensajeBuscarPaciente8 = "";
    Color rojo = new Color(254,54,54);
    
    public buscarPacienteForm() {
        initComponents();
        btnErrorNombre.setVisible(false);
        btnErrorCedula.setVisible(false);
        btnErrorFecha.setVisible(false);
        btnErrorSangre.setVisible(false);
        btnErrorSexo.setVisible(false);
        example.setVisible(false);
        jLabel9.setVisible(false);
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsultarCodigo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        txtNombrePaciente = new javax.swing.JTextField();
        txtCédulaPaciente = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        btnErrorNombre = new javax.swing.JButton();
        btnErrorCedula = new javax.swing.JButton();
        btnErrorFecha = new javax.swing.JButton();
        btnErrorSangre = new javax.swing.JButton();
        btnErrorSexo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTipoSangre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblCodigoPaciente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        example = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        btnConsultarCodigo.setBackground(new java.awt.Color(75, 75, 253));
        btnConsultarCodigo.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnConsultarCodigo.setForeground(new java.awt.Color(254, 254, 254));
        btnConsultarCodigo.setText("Buscar");
        btnConsultarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(75, 75, 253));
        btnLimpiar.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(254, 254, 254));
        btnLimpiar.setText("Limpiar");

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Paciente");

        jLabel2.setForeground(new java.awt.Color(17, 128, 255));
        jLabel2.setText("Escoja los campos con los que se realizará la búsqueda");

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        jRadioButton3.setText("Por nombre");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Por cédula");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        jRadioButton6.setText("Por fecha de nacimiento");
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });

        jRadioButton5.setText("Por tipo de sangre");
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });

        jRadioButton4.setText("Por sexo");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        txtNombrePaciente.setBackground(new java.awt.Color(254, 254, 254));
        txtNombrePaciente.setEnabled(false);
        txtNombrePaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombrePacienteFocusLost(evt);
            }
        });
        txtNombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePacienteKeyTyped(evt);
            }
        });

        txtCédulaPaciente.setBackground(new java.awt.Color(254, 254, 254));
        txtCédulaPaciente.setEnabled(false);
        txtCédulaPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCédulaPacienteFocusLost(evt);
            }
        });
        txtCédulaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCédulaPacienteKeyTyped(evt);
            }
        });

        txtDia.setBackground(new java.awt.Color(254, 254, 254));
        txtDia.setEnabled(false);
        txtDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaFocusLost(evt);
            }
        });
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });

        jLabel16.setText("Día:");

        jLabel19.setText("Mes:");

        txtMes.setBackground(new java.awt.Color(254, 254, 254));
        txtMes.setEnabled(false);
        txtMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesFocusLost(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });

        jLabel20.setText("Año:");

        txtAño.setBackground(new java.awt.Color(254, 254, 254));
        txtAño.setEnabled(false);
        txtAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAñoFocusLost(evt);
            }
        });
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A+", "A-", "O+", "O-", "AB+", "AB-", "B+", "B-" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----", "Masculino", "Femenino" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        btnErrorNombre.setBackground(new java.awt.Color(254, 254, 254));
        btnErrorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        btnErrorNombre.setBorder(null);
        btnErrorNombre.setBorderPainted(false);
        btnErrorNombre.setContentAreaFilled(false);
        btnErrorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorNombreActionPerformed(evt);
            }
        });

        btnErrorCedula.setBackground(new java.awt.Color(254, 254, 254));
        btnErrorCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        btnErrorCedula.setBorder(null);
        btnErrorCedula.setBorderPainted(false);
        btnErrorCedula.setContentAreaFilled(false);
        btnErrorCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorCedulaActionPerformed(evt);
            }
        });

        btnErrorFecha.setBackground(new java.awt.Color(254, 254, 254));
        btnErrorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        btnErrorFecha.setBorder(null);
        btnErrorFecha.setBorderPainted(false);
        btnErrorFecha.setContentAreaFilled(false);
        btnErrorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorFechaActionPerformed(evt);
            }
        });

        btnErrorSangre.setBackground(new java.awt.Color(254, 254, 254));
        btnErrorSangre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        btnErrorSangre.setBorder(null);
        btnErrorSangre.setBorderPainted(false);
        btnErrorSangre.setContentAreaFilled(false);
        btnErrorSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorSangreActionPerformed(evt);
            }
        });

        btnErrorSexo.setBackground(new java.awt.Color(254, 254, 254));
        btnErrorSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        btnErrorSexo.setBorder(null);
        btnErrorSexo.setBorderPainted(false);
        btnErrorSexo.setContentAreaFilled(false);
        btnErrorSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCédulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(3, 3, 3)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(4, 4, 4)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrorSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrorSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnErrorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton3)
                        .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton2)
                        .addComponent(txtCédulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnErrorCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton6)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel19)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnErrorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton5)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnErrorSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnErrorSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
        );

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 18, 18));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("De clic en el ícono");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        jLabel8.setText("Teléfono:");

        lblDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Sexo:");

        lblTipoSangre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Tipo de sangre:");

        lblSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCodigoPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Cédula:");

        jLabel17.setText("Fecha de nacimiento:");

        lblCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Nombre del paciente:");

        jLabel5.setText("Pacientes encontrados:");

        lblNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Dirección:");

        jLabel6.setText("Código del paciente:");

        lblTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFechaNacimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(262, 262, 262))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(597, 597, 597))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel7)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(lblCodigoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        example.setBackground(new java.awt.Color(254, 254, 254));
        example.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paciente/ierror.png"))); // NOI18N
        example.setBorder(null);
        example.setBorderPainted(false);
        example.setContentAreaFilled(false);

        jLabel9.setBackground(new java.awt.Color(254, 254, 254));
        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 18, 18));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("para ver el error");
        jLabel9.setToolTipText("");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConsultarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(example, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(example, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnConsultarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String genero = (String) jComboBox1.getSelectedItem();
        MensajeBuscarPaciente4 = "";
        if (genero.equals("-----"))
        MensajeBuscarPaciente4 += "No se ha seleccionado ningún sexo\n";
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        String tipodeSangre = (String) jComboBox2.getSelectedItem();
        MensajeBuscarPaciente5 = "";
        if (tipodeSangre.equals("--"))
        MensajeBuscarPaciente5 += "No se ha seleccionado ningún tipo de sangre\n";
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        if(txtAño.getText().length()>3)
        evt.consume();
    }//GEN-LAST:event_txtAñoKeyTyped

    private void txtAñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAñoFocusLost
        String anio = txtAño.getText();
        int numanio = 0;
        Calendar actual = Calendar.getInstance();
        int anioActual = actual.get(Calendar.YEAR);
        MensajeBuscarPaciente8 = "";

        if (anio.equals(""))
        MensajeBuscarPaciente8 += "El año no puede estar vacío\n";

        if(!esNumero(anio))
        MensajeBuscarPaciente8 += "El año no puede contener espacios ni caracteres alfabéticos";
        else{
            if(!anio.equals("")){
                numanio = Integer.parseInt(anio);
                if(numanio < 1914 || numanio > anioActual)
                MensajeBuscarPaciente8 += "El año supera al año actual o es menor que el año mínimo aceptado(1914)\n";
            }
        }
    }//GEN-LAST:event_txtAñoFocusLost

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        if(txtMes.getText().length()>1)
        evt.consume();
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesFocusLost
        String mes = txtMes.getText();
        int nummes = 0;
        MensajeBuscarPaciente6 = "";

        if (mes.equals(""))
        MensajeBuscarPaciente6 += "El mes no puede estar vacío\n";

        if(!esNumero(mes))
        MensajeBuscarPaciente6 += "El mes no puede contener espacios ni caracteres alfabéticos\n";
        else{
            if(!mes.equals("")){
                nummes = Integer.parseInt(mes);
                if(nummes < 1 || nummes > 12)
                MensajeBuscarPaciente6 += "El mes solo tiene dígitos entre 1 - 12\n";
            }
        }

    }//GEN-LAST:event_txtMesFocusLost

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        if(txtDia.getText().length()>1)
        evt.consume();
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaFocusLost
        String dia = txtDia.getText();
        int numdia = 0;
        MensajeBuscarPaciente7 = "";

        if (dia.equals(""))
        MensajeBuscarPaciente7 += "El día no puede estar vacío\n";

        if(!esNumero(dia))
        MensajeBuscarPaciente7 += "El día no puede contener espacios ni caracteres alfabéticos\n";
        else{
            if(!dia.equals("")){
                numdia = Integer.parseInt(dia);
                if(numdia < 1 || numdia > 31) // Aquí falta la validación de los meses
                MensajeBuscarPaciente7 += "El día solo tiene dígitos entre 1 - 31\n";// Aquí falta la validación de los meses
            }
        }
    }//GEN-LAST:event_txtDiaFocusLost

    private void txtCédulaPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCédulaPacienteKeyTyped
        if(txtCédulaPaciente.getText().length()>9)
        evt.consume();
    }//GEN-LAST:event_txtCédulaPacienteKeyTyped

    private void txtCédulaPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCédulaPacienteFocusLost
        String cedula = txtCédulaPaciente.getText();
        MensajeBuscarPaciente2 = "";
        if (cedula.equals(""))
        MensajeBuscarPaciente2 += "La cédula del paciente no puede estar vacío\n";
        if (!esNumero(cedula))
        MensajeBuscarPaciente2 += "La cédula del paciente no puede contener espacios en blanco ni caracteres alfabéticos\n";
        if (cedula.length() != 10 && !cedula.equals(""))
        MensajeBuscarPaciente2 += "La cédula del paciente no puede tener menos de 10 dígitos\n";
    }//GEN-LAST:event_txtCédulaPacienteFocusLost

    private void txtNombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePacienteKeyTyped
        if(txtNombrePaciente.getText().length()>49)
        evt.consume();
    }//GEN-LAST:event_txtNombrePacienteKeyTyped

    private void txtNombrePacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrePacienteFocusLost
        String nombre = txtNombrePaciente.getText();
        MensajeBuscarPaciente3 = "";
        if (nombre.equals(""))
        MensajeBuscarPaciente3 += "El nombre del paciente no puede estar vacío\n";
        if (contieneDigito(nombre))
        MensajeBuscarPaciente3 += "El nombre del paciente solo puede contener caracteres alfabéticos\n";
//        if (nombre.length() > 30 && !nombre.equals(""))
//        MensajeBuscarPaciente3 += "El nombre del paciente debe tener una longitud menor que 30 caracteres\n";
    }//GEN-LAST:event_txtNombrePacienteFocusLost

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        if(jRadioButton4.isSelected()){
            jRadioButton6.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton5.setSelected(false);
            jComboBox1.setEnabled(true);
        }else{
            jComboBox1.setEnabled(false);
            jComboBox1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged
        if(jRadioButton5.isSelected()){
            jRadioButton6.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton3.setSelected(false);
            jComboBox2.setEnabled(true);
    }else{
            jComboBox2.setEnabled(false);
            jComboBox2.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
        if(jRadioButton6.isSelected()){
              jRadioButton3.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            txtDia.setEnabled(true);
            txtMes.setEnabled(true);
            txtAño.setEnabled(true);
        }else{
            txtDia.setEnabled(false);
            txtMes.setEnabled(false);
            txtAño.setEnabled(false);
            txtDia.setText("");
            txtMes.setText("");
            txtAño.setText("");
        }
    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        if(jRadioButton2.isSelected()){
            txtCédulaPaciente.setEnabled(true);
          jRadioButton6.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
        }else{
            txtCédulaPaciente.setEnabled(false);
            txtCédulaPaciente.setText("");
        }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
        if(jRadioButton3.isSelected()){
            txtNombrePaciente.setEnabled(true);
            jRadioButton6.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            
        }     else{
            txtNombrePaciente.setEnabled(false);
            txtNombrePaciente.setText("");
        }
        
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void btnConsultarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoActionPerformed

        String cedula = txtCédulaPaciente.getText();
        String nombre = txtNombrePaciente.getText();
        String genero = (String) jComboBox1.getSelectedItem();
        String tipodeSangre = (String) jComboBox2.getSelectedItem();
        String dia = txtDia.getText();
        String mes = txtMes.getText();
        String anio = txtAño.getText();
        MensajeBuscarPaciente = "";

        Connection conexion = conexiondb.conexiondb.getDBConnection();
        ArrayList<Integer>ids_Pacientes = new ArrayList<>();
        if(jRadioButton2.isSelected()){
            jRadioButton6.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            jRadioButton3.setEnabled(false);
            
            if (cedula.equals("")){
                if(MensajeBuscarPaciente2.equals(""))
                    MensajeBuscarPaciente2 += "La cédula del paciente no puede estar vacío\n";
                MensajeBuscarPaciente += "Fallo";
                txtCédulaPaciente.setBackground(rojo);
                btnErrorCedula.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente2.equals("")){
                    txtCédulaPaciente.setBackground(rojo);
                    btnErrorCedula.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }
                else{
                    txtCédulaPaciente.setBackground(java.awt.Color.WHITE);
                    btnErrorCedula.setVisible(false);
                    ids_Pacientes = buscarPaciente_Conexion.getIdsPacientes_porCedula(conexion, txtCédulaPaciente.getText());
                    Vector vector_ids = new Vector(ids_Pacientes);
                    DefaultComboBoxModel model = new DefaultComboBoxModel(vector_ids);
                   jComboBox3.setModel(model);
                }
            }
    }
            else{
            btnErrorCedula.setVisible(false);
            MensajeBuscarPaciente2 = "";
            txtCédulaPaciente.setBackground(java.awt.Color.WHITE);
        }
            

        if(jRadioButton3.isSelected()){
            
            jRadioButton2.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            jRadioButton6.setEnabled(false);
            
            if (nombre.equals("")){
                if(MensajeBuscarPaciente3.equals(""))
                    MensajeBuscarPaciente3 += "El nombre del paciente no puede estar vacío\n";
                MensajeBuscarPaciente += "Fallo";
                txtNombrePaciente.setBackground(rojo);
                btnErrorNombre.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente3.equals("")){
                    txtNombrePaciente.setBackground(rojo);
                    btnErrorNombre.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }
                else{
                    
                    txtNombrePaciente.setBackground(java.awt.Color.WHITE);
                    ids_Pacientes = buscarPaciente_Conexion.getIdsPacientes_porNombre(conexion, txtNombrePaciente.getText());
                    Vector vector_ids = new Vector(ids_Pacientes);
                    DefaultComboBoxModel model = new DefaultComboBoxModel(vector_ids);
                   jComboBox3.setModel(model);
                    btnErrorNombre.setVisible(false);
                }
            }
    }else{
            btnErrorNombre.setVisible(false);
            MensajeBuscarPaciente3 = "";
            txtNombrePaciente.setBackground(java.awt.Color.WHITE);
        }

        if(jRadioButton4.isSelected()){
            
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton5.setEnabled(false);
            
            if (genero.equals("-----")){
                if(MensajeBuscarPaciente4.equals(""))
                    MensajeBuscarPaciente4 += "No se ha seleccionado ningún sexo\n";
                MensajeBuscarPaciente += "Fallo";
                btnErrorSexo.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente4.equals("")){
                    btnErrorSexo.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }else
                    
                    btnErrorSexo.setVisible(false);
                    int id_sexo_= 0;
                    String id_sex = (String)jComboBox1.getSelectedItem();
                    if(id_sex.equals("Femenino"))
                        id_sexo_= 1;
                    if(id_sex.equals("Masculino"))
                        id_sexo_ =2;
                    ids_Pacientes = buscarPaciente_Conexion.getIdsPacientes_porSexo(conexion,id_sexo_);
                    Vector vector_ids = new Vector(ids_Pacientes);
                    DefaultComboBoxModel model = new DefaultComboBoxModel(vector_ids);
                   jComboBox3.setModel(model);
            }
    }
            else{
            MensajeBuscarPaciente4 = "";
            btnErrorSexo.setVisible(false);
        }

        if(jRadioButton5.isSelected()){
            
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton6.setEnabled(false);
            
            if (tipodeSangre.equals("--")){
                if(MensajeBuscarPaciente5.equals(""))
                    MensajeBuscarPaciente5 += "No se ha seleccionado ningún tipo de sangre\n";
                MensajeBuscarPaciente += "Fallo";
                btnErrorSangre.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente5.equals("")){
                    btnErrorSangre.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }else{
                    
                    btnErrorSangre.setVisible(false);
            int id_sangre_ = 0;
            String sangre= (String)jComboBox2.getSelectedItem();
            if(sangre.equals("A+"))
                id_sangre_ = 1;
            if(sangre.equals("A-"))
                id_sangre_ = 2;
            if(sangre.equals("O+"))
                id_sangre_ = 3;
            if(sangre.equals("O-"))
                id_sangre_ = 4;
            if(sangre.equals("B+"))
                id_sangre_ = 5;
            if(sangre.equals("B-"))
                id_sangre_ = 6;
            if(sangre.equals("AB+"))
                id_sangre_ = 7;
            if(sangre.equals("AB-"))
                id_sangre_ = 8;
            
                ids_Pacientes = buscarPaciente_Conexion.getIdsPacientes_porSangre(conexion,id_sangre_);
                Vector vector_ids = new Vector(ids_Pacientes);
                DefaultComboBoxModel model = new DefaultComboBoxModel(vector_ids);
                jComboBox3.setModel(model);
        }
            }
    }else{
            MensajeBuscarPaciente5 = "";
            btnErrorSangre.setVisible(false);
        }


        if(jRadioButton6.isSelected()){
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            
            if (dia.equals("")){
                if(MensajeBuscarPaciente7.equals(""))
                    MensajeBuscarPaciente7 += "El día no puede estar vacío\n";
                MensajeBuscarPaciente += "Fallo";
                txtDia.setBackground(rojo);
                btnErrorFecha.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente7.equals("")){
                    txtDia.setBackground(rojo);
                    btnErrorFecha.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }else
                    txtDia.setBackground(java.awt.Color.WHITE);
            }

            if (mes.equals("")){
                if(MensajeBuscarPaciente6.equals(""))
                    MensajeBuscarPaciente6 += "El mes no puede estar vacío\n";
                MensajeBuscarPaciente += "Fallo";
                txtMes.setBackground(rojo);
                btnErrorFecha.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente6.equals("")){
                    txtMes.setBackground(rojo);
                    btnErrorFecha.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }else
                    txtMes.setBackground(java.awt.Color.WHITE);
            }

            if (anio.equals("")){
                if(MensajeBuscarPaciente8.equals(""))
                    MensajeBuscarPaciente8 += "El campo año en la fecha de nacimiento no puede estar vacío\n";
                MensajeBuscarPaciente += "Fallo";
                txtAño.setBackground(rojo);
                btnErrorFecha.setVisible(true);
                example.setVisible(true);
                jLabel9.setVisible(true);
                jLabel4.setVisible(true);
            }else{
                if(!MensajeBuscarPaciente8.equals("")){
                    txtAño.setBackground(rojo);
                    btnErrorFecha.setVisible(true);
                    example.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel4.setVisible(true);
                }else
                    txtAño.setBackground(java.awt.Color.WHITE);
            }
        
            if(MensajeBuscarPaciente6.equals("") && MensajeBuscarPaciente7.equals("") && MensajeBuscarPaciente8.equals(""))
                btnErrorFecha.setVisible(false);
                Date fecha_a_ingresar = new Date(Integer.parseInt(txtAño.getText())-1900,Integer.parseInt(txtMes.getText())-1,Integer.parseInt(txtDia.getText()));
                ids_Pacientes = buscarPaciente_Conexion.getIdsPacientes_porFecha(conexion,fecha_a_ingresar);
                Vector vector_ids = new Vector(ids_Pacientes);
                DefaultComboBoxModel model = new DefaultComboBoxModel(vector_ids);
                jComboBox3.setModel(model);
        }
        else{
            MensajeBuscarPaciente6 = "";
            MensajeBuscarPaciente7 = "";
            MensajeBuscarPaciente8 = "";
            btnErrorFecha.setVisible(false);
            txtDia.setBackground(java.awt.Color.WHITE);
            txtMes.setBackground(java.awt.Color.WHITE);
            txtAño.setBackground(java.awt.Color.WHITE);
        }
        
        if(!jRadioButton2.isSelected() && !jRadioButton3.isSelected() && !jRadioButton4.isSelected() && !jRadioButton5.isSelected()&& !jRadioButton6.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "No se ha escogido ningún campo para realizar la búsqueda", "Advertencia", 2);
            example.setVisible(false);
            jLabel9.setVisible(false);
            jLabel4.setVisible(false);
        }else{
            MensajeBuscarPaciente = MensajeBuscarPaciente2 + MensajeBuscarPaciente3 + MensajeBuscarPaciente4 + MensajeBuscarPaciente5 + MensajeBuscarPaciente6 + MensajeBuscarPaciente7 + MensajeBuscarPaciente8;
            if(MensajeBuscarPaciente.equals("")){
                example.setVisible(false);
                jLabel9.setVisible(false);
                jLabel4.setVisible(false);
            }
            if(MensajeBuscarPaciente.equals(""))
                JOptionPane.showMessageDialog(rootPane, "Buscando....", "Mensaje", 1);
            else
                JOptionPane.showMessageDialog(rootPane, "No se puede buscar, algunos campos tienen errores", "Mensaje", 1);
        }


    }//GEN-LAST:event_btnConsultarCodigoActionPerformed

    private void btnErrorCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorCedulaActionPerformed
        JOptionPane.showMessageDialog(rootPane, MensajeBuscarPaciente2);
    }//GEN-LAST:event_btnErrorCedulaActionPerformed

    private void btnErrorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorNombreActionPerformed
        JOptionPane.showMessageDialog(rootPane, MensajeBuscarPaciente3);
    }//GEN-LAST:event_btnErrorNombreActionPerformed

    private void btnErrorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorFechaActionPerformed
        JOptionPane.showMessageDialog(rootPane, MensajeBuscarPaciente6+MensajeBuscarPaciente7+MensajeBuscarPaciente8);
    }//GEN-LAST:event_btnErrorFechaActionPerformed

    private void btnErrorSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorSangreActionPerformed
        JOptionPane.showMessageDialog(rootPane, MensajeBuscarPaciente5);
    }//GEN-LAST:event_btnErrorSangreActionPerformed

    private void btnErrorSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorSexoActionPerformed
        JOptionPane.showMessageDialog(rootPane, MensajeBuscarPaciente4);
    }//GEN-LAST:event_btnErrorSexoActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        ArrayList<Object> paciente = new ArrayList<>();
        int id_paciente = (int)jComboBox3.getSelectedItem();
        Connection conexion = conexiondb.conexiondb.getDBConnection();
        paciente = buscarPaciente_Conexion.getPaciente(conexion, id_paciente);
        Date fecha_=(Date)paciente.get(2);
        
        lblCedula.setText((String)paciente.get(0));
        lblDireccion.setText((String)paciente.get(1));
        lblFechaNacimiento.setText(fecha_.toString());
        lblTipoSangre.setText((String)paciente.get(3));
        lblSexo.setText((String)paciente.get(4));
        lblNombrePaciente.setText((String)paciente.get(5));
        lblTelefono.setText((String)paciente.get(6));
        lblCodigoPaciente.setText(String.valueOf(id_paciente));
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarPacienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarPacienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarPacienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarPacienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarPacienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCodigo;
    private javax.swing.JButton btnErrorCedula;
    private javax.swing.JButton btnErrorFecha;
    private javax.swing.JButton btnErrorNombre;
    private javax.swing.JButton btnErrorSangre;
    private javax.swing.JButton btnErrorSexo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton example;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigoPaciente;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCédulaPaciente;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombrePaciente;
    // End of variables declaration//GEN-END:variables

    public boolean esNumero(String str) {
        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

    public boolean contieneDigito(String str) {

        for (char c : str.toCharArray()) {
            if (Character.isDigit(c) || str.equals("")) {
                return true;
            }
        }
        return false;
    }

}
