/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fichaMedica;

import java.util.Calendar;
import javax.swing.JOptionPane;

//===
import java.sql.*;
import conexiondb.*;

/**
 *
 * @author j3s
 */
public class registroFichaForm extends javax.swing.JFrame {

    /**
     * Creates new form registroFichaForm
     */

    public static String MensajeRegistrarFicha = "";
    public static String MensajeRegistrarFicha1 = "";
    public static String MensajeRegistrarFicha2 = "";
    public static String MensajeRegistrarFicha3 = "";
    public static String MensajeRegistrarFicha4 = "";
    public static String MensajeRegistrarFicha5 = "";
    public static String MensajeRegistrarFicha6 = "";
    public static String MensajeRegistrarFicha7 = "";
    public static String MensajeRegistrarFicha8 = "";
    public static String MensajeRegistrarFicha9 = "";

    public registroFichaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedula = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        btnConsultarCodigo = new javax.swing.JButton();
        lblNombrePaciente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPresionArterialSis = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPresionArterialDias = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFreqCard = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFreqResp = new javax.swing.JTextField();
        txtRegistro = new javax.swing.JButton();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Código del paciente:");

        txtCodigoPaciente.setBackground(new java.awt.Color(254, 254, 254));
        txtCodigoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPacienteKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 24)); // NOI18N
        jLabel1.setText("Nueva Ficha Médica");

        jLabel2.setText("Código de la ficha:");

        jLabel6.setText("Nombre del paciente:");

        lblCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnConsultarCodigo.setText("Consultar");
        btnConsultarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoActionPerformed(evt);
            }
        });

        lblNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Cédula del paciente:");

        jLabel3.setText("Estatura:");

        txtEstatura.setBackground(new java.awt.Color(254, 254, 254));
        txtEstatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEstaturaFocusLost(evt);
            }
        });
        txtEstatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstaturaKeyReleased(evt);
            }
        });

        jLabel12.setText("Fecha de registro:");

        jLabel13.setText("Peso:");

        txtPeso.setBackground(new java.awt.Color(254, 254, 254));
        txtPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesoFocusLost(evt);
            }
        });
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoKeyReleased(evt);
            }
        });

        jLabel14.setText("Presión Arterial Sistólica:");

        txtPresionArterialSis.setBackground(new java.awt.Color(254, 254, 254));
        txtPresionArterialSis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPresionArterialSisFocusLost(evt);
            }
        });
        txtPresionArterialSis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPresionArterialSisKeyReleased(evt);
            }
        });

        jLabel15.setText("Presión Arterial Diastólica:");

        txtPresionArterialDias.setBackground(new java.awt.Color(254, 254, 254));
        txtPresionArterialDias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPresionArterialDiasFocusLost(evt);
            }
        });
        txtPresionArterialDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPresionArterialDiasKeyReleased(evt);
            }
        });

        jLabel16.setText("Frecuencia cardiaca:");

        txtFreqCard.setBackground(new java.awt.Color(254, 254, 254));
        txtFreqCard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFreqCardFocusLost(evt);
            }
        });
        txtFreqCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFreqCardKeyReleased(evt);
            }
        });

        jLabel17.setText("Frecuencia Respiratoria:");

        txtFreqResp.setBackground(new java.awt.Color(254, 254, 254));
        txtFreqResp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFreqRespFocusLost(evt);
            }
        });
        txtFreqResp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFreqRespKeyReleased(evt);
            }
        });

        txtRegistro.setText("Registrar Ficha Médica");
        txtRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroActionPerformed(evt);
            }
        });

        txtMes.setBackground(new java.awt.Color(254, 254, 254));
        txtMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesFocusLost(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesKeyReleased(evt);
            }
        });

        txtDia.setBackground(new java.awt.Color(254, 254, 254));
        txtDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaFocusLost(evt);
            }
        });
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaKeyReleased(evt);
            }
        });

        jLabel4.setText("Día:");

        jLabel5.setText("Mes:");

        jLabel9.setText("Año:");

        txtAño.setBackground(new java.awt.Color(254, 254, 254));
        txtAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAñoFocusLost(evt);
            }
        });
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAñoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPresionArterialSis, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPresionArterialDias, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(56, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtRegistro)
                                        .addGap(45, 45, 45))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFreqCard, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultarCodigo))
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFreqResp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(2, 2, 2)
                                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPresionArterialSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPresionArterialDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtRegistro)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFreqCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFreqResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtAño))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoActionPerformed
        String codigoPac = txtCodigoPaciente.getText();
        if (codigoPac.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El código del paciente no puede estar vacío", "Advertencia", 2);
            txtCodigoPaciente.setBackground(java.awt.Color.PINK);
        }else if (!esNumero(codigoPac)){
            JOptionPane.showMessageDialog(rootPane, "El código del paciente no puede contener espacios en blanco ni caracteres alfabéticos", "Advertencia", 2);
            txtCodigoPaciente.setBackground(java.awt.Color.PINK);
        }else
            txtCodigoPaciente.setBackground(java.awt.Color.WHITE);

//===
		if(consultarFicha(codigoPac)){
		}else{
			JOptionPane.showMessageDialog(rootPane, "No encontrado", "Advertencia", 2);
		}
    }//GEN-LAST:event_btnConsultarCodigoActionPerformed

    private void txtRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroActionPerformed
        String estatura = txtEstatura.getText();
        String peso = txtPeso.getText();
        String presionAsis = txtPresionArterialSis.getText();
        String presionDias = txtPresionArterialDias.getText();
        String freqCard = txtFreqCard.getText();
        String freqResp = txtFreqResp.getText();
        String dia = txtDia.getText();
        String mes = txtMes.getText();
        String anio = txtAño.getText();
        MensajeRegistrarFicha = "";
        MensajeRegistrarFicha = MensajeRegistrarFicha1 + MensajeRegistrarFicha2 + MensajeRegistrarFicha3 + MensajeRegistrarFicha4 + MensajeRegistrarFicha5 + MensajeRegistrarFicha6 + MensajeRegistrarFicha7 + MensajeRegistrarFicha8 + MensajeRegistrarFicha9;

        if (estatura.equals("") && MensajeRegistrarFicha1.equals("")){
            MensajeRegistrarFicha += "El campo estatura no puede estar vacío\n";
            txtEstatura.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha1.equals(""))
                txtEstatura.setBackground(java.awt.Color.PINK);
            else
                txtEstatura.setBackground(java.awt.Color.WHITE);
        }

        if (peso.equals("") && MensajeRegistrarFicha2.equals("")){
            MensajeRegistrarFicha += "El campo peso no puede estar vacío\n";
            txtPeso.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha2.equals(""))
                txtPeso.setBackground(java.awt.Color.PINK);
            else
                txtPeso.setBackground(java.awt.Color.WHITE);
        }

        if (presionAsis.equals("") && MensajeRegistrarFicha3.equals("")){
            MensajeRegistrarFicha += "El campo presión sistólica no puede estar vacío\n";
            txtPresionArterialSis.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha3.equals(""))
                txtPresionArterialSis.setBackground(java.awt.Color.PINK);
            else
                txtPresionArterialSis.setBackground(java.awt.Color.WHITE);
        }

        if (presionDias.equals("") && MensajeRegistrarFicha4.equals("")){
            MensajeRegistrarFicha += "El campo presión diastólica no puede estar vacío\n";
            txtPresionArterialDias.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha4.equals(""))
                txtPresionArterialDias.setBackground(java.awt.Color.PINK);
            else
                txtPresionArterialDias.setBackground(java.awt.Color.WHITE);
        }

        if (freqCard.equals("") && MensajeRegistrarFicha5.equals("")){
            MensajeRegistrarFicha += "El campo frecuencia cardiaca no puede estar vacío\n";
            txtFreqCard.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha5.equals(""))
                txtFreqCard.setBackground(java.awt.Color.PINK);
            else
                txtFreqCard.setBackground(java.awt.Color.WHITE);
        }

        if (freqResp.equals("") && MensajeRegistrarFicha6.equals("")){
            MensajeRegistrarFicha += "El campo frecuencia respiratoria no puede estar vacío\n";
            txtFreqResp.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha6.equals(""))
                txtFreqResp.setBackground(java.awt.Color.PINK);
            else
                txtFreqResp.setBackground(java.awt.Color.WHITE);
        }

        if (dia.equals("") && MensajeRegistrarFicha7.equals("")){
            MensajeRegistrarFicha += "El campo día no puede estar vacío\n";
            txtDia.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha7.equals(""))
                txtDia.setBackground(java.awt.Color.PINK);
            else
                txtDia.setBackground(java.awt.Color.WHITE);
        }

        if (mes.equals("") && MensajeRegistrarFicha8.equals("")){
            MensajeRegistrarFicha += "El campo mes no puede estar vacío\n";
            txtMes.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha8.equals(""))
                txtMes.setBackground(java.awt.Color.PINK);
            else
                txtMes.setBackground(java.awt.Color.WHITE);
        }

        if (anio.equals("") && MensajeRegistrarFicha9.equals("")){
            MensajeRegistrarFicha += "El campo año no puede estar vacío\n";
            txtAño.setBackground(java.awt.Color.PINK);
        }else{
            if(!MensajeRegistrarFicha9.equals(""))
                txtAño.setBackground(java.awt.Color.PINK);
            else
                txtAño.setBackground(java.awt.Color.WHITE);
        }

        if(MensajeRegistrarFicha.equals("")){
//==
			registrarFicha();
            JOptionPane.showMessageDialog(rootPane, "Registro exitoso", "Mensaje", 1);
        }else
            JOptionPane.showMessageDialog(rootPane, MensajeRegistrarFicha, "Advertencia", 2);

    }//GEN-LAST:event_txtRegistroActionPerformed

    private void txtCodigoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPacienteKeyReleased
//        String codigo = txtCodigoPaciente.getText();
//        if(!esNumero(codigo))
//            txtCodigoPaciente.setText("");
//        try
//        {
//            int codigoInt = Integer.parseInt(codigo);
//            if(codigoInt<0|| codigoInt>999999999)
//                txtCodigoPaciente.setText("");
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtCodigoPacienteKeyReleased

    private void txtEstaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstaturaKeyReleased
//        String estatura = txtEstatura.getText();
//        if(!esNumero(estatura))
//            txtEstatura.setText("");
//        try
//        {
//            int estaturaInt = Integer.parseInt(estatura);
//            if(estaturaInt<1|| estaturaInt>270)
//                txtEstatura.setText("");
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtEstaturaKeyReleased

    private void txtPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyReleased
//        String peso = txtPeso.getText();
//        if(!esNumero(peso))
//            txtPeso.setText("");
//        try
//        {
//            int pesoInt = Integer.parseInt(peso);
//            if(pesoInt<1|| pesoInt>500)
//                txtPeso.setText("");
//
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtPesoKeyReleased

    private void txtPresionArterialSisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresionArterialSisKeyReleased
//        String presion = txtPresionArterialSis.getText();
//        if(!esNumero(presion))
//            txtPresionArterialSis.setText("");
//        try
//        {
//            int presionInt = Integer.parseInt(presion);
//            if(presionInt<1|| presionInt>500)
//                txtPresionArterialSis.setText("");
//
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtPresionArterialSisKeyReleased

    private void txtPresionArterialDiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresionArterialDiasKeyReleased
//        String presion = txtPresionArterialDias.getText();
//        if(!esNumero(presion))
//            txtPresionArterialDias.setText("");
//        try
//        {
//            int presionInt = Integer.parseInt(presion);
//            if(presionInt<1|| presionInt>500)
//                txtPresionArterialDias.setText("");
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtPresionArterialDiasKeyReleased

    private void txtFreqCardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFreqCardKeyReleased
//        String frecuencia = txtFreqCard.getText();
//        if(!esNumero(frecuencia))
//            txtFreqCard.setText("");
//        try
//        {
//            int frecuenciaInt = Integer.parseInt(frecuencia);
//            if(frecuenciaInt<1|| frecuenciaInt>500)
//                txtFreqCard.setText("");
//
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtFreqCardKeyReleased

    private void txtFreqRespKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFreqRespKeyReleased
//        String frecuencia = txtFreqResp.getText();
//        if(!esNumero(frecuencia))
//            txtFreqResp.setText("");
//        try
//        {
//            int frecuenciaInt = Integer.parseInt(frecuencia);
//            if(frecuenciaInt<1|| frecuenciaInt>500)
//                txtFreqResp.setText("");
//
//
//        }catch(Exception e)
//        {}
    }//GEN-LAST:event_txtFreqRespKeyReleased

    private void txtMesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyReleased
//        String mes = txtMes.getText();
//
//        if(!esNumero(mes))
//        {
//            txtMes.setText("");
//        }
//        try
//        {
//            int mesInt = Integer.parseInt(mes);
//            if(mesInt <1 || mesInt>12)
//            txtMes.setText("");
//
//        }catch(Exception e)
//        {
//
//        }
    }//GEN-LAST:event_txtMesKeyReleased

    private void txtDiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyReleased
//        String dia = txtDia.getText();
//
//        if(!esNumero(dia))
//        {
//            txtDia.setText("");
//        }
//        try
//        {
//            int diaInt = Integer.parseInt(dia);
//            if(diaInt <1 || diaInt>31)
//            txtDia.setText("");
//
//        }catch(Exception e)
//        {
//
//        }
    }//GEN-LAST:event_txtDiaKeyReleased

    private void txtAñoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyReleased
//        Calendar actual = Calendar.getInstance();
//        int añoActual = actual.get(Calendar.YEAR);
//        String año = txtAño.getText();
//
//        if(!esNumero(año))
//        {
//            txtAño.setText("");
//        }
//        try
//        {
//
//            int añoInt = Integer.parseInt(año);
//            if(añoActual > añoInt)
//                txtAño.setText("");
//            if(añoInt <0|| añoInt>2020)
//            txtAño.setText("");
//
//        }catch(Exception e)
//        {
//
//        }
    }//GEN-LAST:event_txtAñoKeyReleased

    private void txtEstaturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstaturaFocusLost
        String estatura = txtEstatura.getText();
        MensajeRegistrarFicha1 = "";
        int estaturaNum = 0;

        if(estatura.equals(""))
            MensajeRegistrarFicha1 += "El campo estatura está vacío\n";

        if(!esNumero(estatura))
            MensajeRegistrarFicha1 += "El campo estatura solo puede estar formado por números\n";
        else{
            estaturaNum = Integer.parseInt(estatura);
            if(estaturaNum<1|| estaturaNum>270)//Buscar estatura mínima y máximo
            MensajeRegistrarFicha1 += "El campo estatura se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtEstaturaFocusLost

    private void txtPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesoFocusLost
        String peso = txtPeso.getText();
        MensajeRegistrarFicha2 = "";
        int pesoNum = 0;

        if(peso.equals(""))
            MensajeRegistrarFicha2 += "El campo peso está vacío\n";

        if(!esNumero(peso))
            MensajeRegistrarFicha2 += "El campo peso solo puede estar formado por números\n";
        else{
            pesoNum = Integer.parseInt(peso);
            if(pesoNum<1|| pesoNum>500)//Buscar peso mínima y máximo
            MensajeRegistrarFicha2 += "El campo peso se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtPesoFocusLost

    private void txtPresionArterialSisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPresionArterialSisFocusLost
        String presion = txtPresionArterialSis.getText();
        MensajeRegistrarFicha3 = "";
        int presionNum = 0;

        if(presion.equals(""))
            MensajeRegistrarFicha3 += "El campo presión arterial sistólica está vacío\n";

        if(!esNumero(presion))
            MensajeRegistrarFicha3 += "El campo presión arterial sistólica solo puede estar formado por números\n";
        else{
            presionNum = Integer.parseInt(presion);
            if(presionNum<1|| presionNum>160)//Buscar presión mínima y máximo
            MensajeRegistrarFicha3 += "El campo presión arterial sistólica se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtPresionArterialSisFocusLost

    private void txtPresionArterialDiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPresionArterialDiasFocusLost
        String presion = txtPresionArterialDias.getText();
        MensajeRegistrarFicha4 = "";
        int presionNum = 0;

        if(presion.equals(""))
            MensajeRegistrarFicha4 += "El campo presión arterial diastólica está vacío\n";

        if(!esNumero(presion))
            MensajeRegistrarFicha4 += "El campo presión arterial diastólica solo puede estar formado por números\n";
        else{
            presionNum = Integer.parseInt(presion);
            if(presionNum<1|| presionNum>160)//Buscar presión mínima y máximo
            MensajeRegistrarFicha4 += "El campo presión arterial diastólica se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtPresionArterialDiasFocusLost

    private void txtFreqCardFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFreqCardFocusLost
        String freq = txtFreqCard.getText();
        MensajeRegistrarFicha5 = "";
        int freqNum = 0;

        if(freq.equals(""))
            MensajeRegistrarFicha5 += "El campo frecuencia cardiaca está vacío\n";

        if(!esNumero(freq))
            MensajeRegistrarFicha5 += "El campo frecuencia cardiaca solo puede estar formado por números\n";
        else{
            freqNum = Integer.parseInt(freq);
            if(freqNum<50|| freqNum>100)//Buscar frecuencia mínima y máximo
            MensajeRegistrarFicha5 += "El campo frecuencia cardiaca se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtFreqCardFocusLost

    private void txtFreqRespFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFreqRespFocusLost
        String freq = txtFreqResp.getText();
        MensajeRegistrarFicha6 = "";
        int freqNum = 0;

        if(freq.equals(""))
            MensajeRegistrarFicha6 += "El campo frecuencia respiratoria está vacío\n";

        if(!esNumero(freq))
            MensajeRegistrarFicha6 += "El campo frecuencia respiratoria solo puede estar formado por números\n";
        else{
            freqNum = Integer.parseInt(freq);
            if(freqNum<50|| freqNum>100)//Buscar frecuencia mínima y máximo
            MensajeRegistrarFicha6 += "El campo frecuencia respiratoria se encuentra fuera del rango\n";
        }
    }//GEN-LAST:event_txtFreqRespFocusLost

    private void txtDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaFocusLost
        String dia = txtDia.getText();
        int numdia = 0;
        String mes = txtMes.getText();
        String año = txtAño.getText();
        Calendar actual = Calendar.getInstance();
        int añoActual = actual.get(Calendar.YEAR);
        int diaActual = actual.get(Calendar.DAY_OF_MONTH);
        int mesActual = actual.get(Calendar.MONTH) + 1;
        MensajeRegistrarFicha7 = "";

        if (dia.equals(""))
            MensajeRegistrarFicha7 += "El campo día de la fecha de nacimiento no puede estar vacío\n";

        if(!esNumero(dia))
            MensajeRegistrarFicha7 += "El día no puede contener espacios ni caracteres alfabéticos\n";
        else{
            if(!dia.equals("")){
                numdia = Integer.parseInt(dia);
                if(numdia < 1 || numdia > 31) // Aquí falta la validación de los meses
                    MensajeRegistrarFicha7 += "El día solo tiene dígitos entre 1 - 31\n";// Aquí falta la validación de los meses
            }
        }

        if(!dia.equals("") && !mes.equals("") && !año.equals("") && esNumero(mes) && esNumero(año) && esNumero(dia) && (Integer.parseInt(mes)<12 && Integer.parseInt(mes)>0)){
            if(Integer.parseInt(año) == añoActual && Integer.parseInt(mes) == mesActual){
                if(Integer.parseInt(dia) < diaActual){
                    MensajeRegistrarFicha7 += "Día inválido: Se ha escogido un día anterior al actual\n";
                }
            }else if(Integer.parseInt(año) == añoActual && Integer.parseInt(mes) > mesActual){
                if(Integer.parseInt(dia) < 0 || Integer.parseInt(dia) > 31){
                    MensajeRegistrarFicha7 += "Día Inválido: Solo puede tomar el valor de 1 - 31\n";
                }
            }else if(Integer.parseInt(año) > añoActual){
                if(Integer.parseInt(dia) < 0 || Integer.parseInt(dia) > 31){
                    MensajeRegistrarFicha7 += "Día Inválido: Solo puede tomar el valor de 1 - 31\n";
                }
            }
        }
    }//GEN-LAST:event_txtDiaFocusLost

    private void txtMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesFocusLost
        String mes = txtMes.getText();
        String año = txtAño.getText();
        String dia = txtDia.getText();
        int nummes = 0;
        Calendar actual = Calendar.getInstance();
        int añoActual = actual.get(Calendar.YEAR);
        int diaActual = actual.get(Calendar.DAY_OF_MONTH);
        int mesActual = actual.get(Calendar.MONTH) + 1;
        MensajeRegistrarFicha8 = "";

        if (mes.equals(""))
            MensajeRegistrarFicha8 += "El campo mes de la fecha de nacimiento no puede estar vacío\n";

        if(!esNumero(mes))
            MensajeRegistrarFicha8 += "El mes no puede contener espacios ni caracteres alfabéticos\n";
        else{
            if(!mes.equals("")){
                nummes = Integer.parseInt(mes);
                if(nummes < 1 || nummes > 12)
                    MensajeRegistrarFicha8 += "El mes solo tiene dígitos entre 1 - 12\n";
            }
        }

        if(!año.equals("") && !mes.equals("") && esNumero(año) && esNumero(mes) && (Integer.parseInt(mes)<12 && Integer.parseInt(mes)>0)){
            if(Integer.parseInt(año) == añoActual) {
                if(Integer.parseInt(mes) < mesActual){
                    MensajeRegistrarFicha8 += "Mes inválido: Se ha escogido un mes anterior al actual\n";
                }
            }else if(Integer.parseInt(año) > añoActual){
                if(Integer.parseInt(mes)<1 || Integer.parseInt(mes)>12){
                    MensajeRegistrarFicha8 += "Mes inválido: Solo puede tomar el valor de 1 - 12l\n";
                }
            }
        }
    }//GEN-LAST:event_txtMesFocusLost

    private void txtAñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAñoFocusLost
        String anio = txtAño.getText();
        String mes = txtMes.getText();
        String dia = txtDia.getText();
        int numanio = 0;
        Calendar actual = Calendar.getInstance();
        int añoActual = actual.get(Calendar.YEAR);
        int diaActual = actual.get(Calendar.DAY_OF_MONTH);
        int mesActual = actual.get(Calendar.MONTH) + 1;
        MensajeRegistrarFicha9 = "";

        if (anio.equals(""))
            MensajeRegistrarFicha9 += "El campo año de la fecha de nacimiento no puede estar vacío\n";

        if(!esNumero(anio))
            MensajeRegistrarFicha9 += "El año no puede contener espacios ni caracteres alfabéticos\n";
        else{
            if(!anio.equals("")){
                numanio = Integer.parseInt(anio);
                if(numanio < 1914 || numanio > añoActual)
                    MensajeRegistrarFicha9 += "Año no válido\n";
            }
        }
    }//GEN-LAST:event_txtAñoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroFichaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroFichaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroFichaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroFichaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroFichaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCodigoPaciente;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtFreqCard;
    private javax.swing.JTextField txtFreqResp;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPresionArterialDias;
    private javax.swing.JTextField txtPresionArterialSis;
    private javax.swing.JButton txtRegistro;
    // End of variables declaration//GEN-END:variables

    public boolean esNumero(String str) {
        for (char c: str.toCharArray())
        {
            if (!Character.isDigit(c))
                    return false;
        }
        return true;
    }

//===
	public boolean consultarFicha(String cedula){
		boolean valido = false;


		Connection conn = null;
		CallableStatement stmt = null;

		try{
		conn = conexiondb.getDBConnection();

		String sql = "{call sp_paciente_select_cedula(?)}";
		stmt = conn.prepareCall(sql);
		stmt.setString(1, cedula);
		stmt.execute();

		ResultSet rs = stmt.getResultSet();
		valido = rs.next();
		if(valido){
			this.lblNombrePaciente.setText(rs.getString("nombre") + " " + rs.getString("apellido"));
			this.lblCedula.setText(rs.getString("cedula"));
			//this.lblCodigo.setText(rs.getString("ficha"));
		}else{
			this.lblNombrePaciente.setText("");
			this.lblCedula.setText("");
			//this.lblCodigo.setText("");
		}
		rs.close();

		stmt.close();
		conn.close();
		}catch(SQLException se){
			se.printStackTrace();
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			try{
				if(stmt!=null) stmt.close();
			}catch(SQLException se2){
			}
			try{
				if(conn!=null) conn.close();
			}catch(SQLException se){
				se.printStackTrace();
			}
		}


		return valido;

	}

	public boolean registrarFicha(){
		boolean valido = false;
		int codigo = 0;


		Connection conn = null;
		CallableStatement stmt = null;

		try{
		conn = conexiondb.getDBConnection();

		String sql = "{call sp_ficha_medica_insert_cedula(?,?,?,?,?,?,?,?,?)}";
		stmt = conn.prepareCall(sql);
		stmt.setString(1, this.lblCedula.getText());
		stmt.setString(2, this.txtEstatura.getText());
		stmt.setString(3, this.txtPeso.getText());
		stmt.setString(4, this.txtPresionArterialSis.getText());
		stmt.setString(5, this.txtPresionArterialDias.getText());
		stmt.setString(6, this.txtFreqCard.getText());
		stmt.setString(7, this.txtFreqResp.getText());
		stmt.setString(8, this.txtAño.getText() + "-" + this.txtMes.getText() + "-" + this.txtDia.getText());
		stmt.registerOutParameter(9, java.sql.Types.INTEGER);
		valido = stmt.execute();
		//valido = true;
		codigo = stmt.getInt(9);
		this.lblCodigo.setText("" + codigo);

		stmt.close();
		conn.close();
		}catch(SQLException se){
			se.printStackTrace();
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			try{
				if(stmt!=null) stmt.close();
			}catch(SQLException se2){
			}
			try{
				if(conn!=null) conn.close();
			}catch(SQLException se){
				se.printStackTrace();
			}
		}


		return valido;

	}

}
