/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//Si usa MySQL comentar el código de la línea 570 y descomentar el código de la línea 572

package citaMedica;

//===
//import conexion.conexiondb;
import conexiondb.*;

import Paciente.registrarPacienteForm;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.Date;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author j3s
 */
public class nuevaCitaForm extends javax.swing.JFrame {

    Color rojo = new Color(254,54,54);

    /**
     * Creates new form nuevaCitaForm
     */
    public nuevaCitaForm() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        btnConsultarCodigo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGenerarCita = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblCodigoPaciente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaPaciente = new javax.swing.JTextField();
        btnRegistrarPaciente = new javax.swing.JButton();
        checkRegistro = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHorasDisponibles = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        lblCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnConsultarCodigo.setBackground(new java.awt.Color(75, 75, 253));
        btnConsultarCodigo.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnConsultarCodigo.setForeground(new java.awt.Color(254, 254, 254));
        btnConsultarCodigo.setText("Consultar");
        btnConsultarCodigo.setEnabled(false);
        btnConsultarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        lblNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Turno / Hora:");

        btnGenerarCita.setBackground(new java.awt.Color(75, 75, 253));
        btnGenerarCita.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnGenerarCita.setForeground(new java.awt.Color(254, 254, 254));
        btnGenerarCita.setText("Generar Nueva Cita");
        btnGenerarCita.setEnabled(false);
        btnGenerarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCitaActionPerformed(evt);
            }
        });

        jLabel7.setText("Código del paciente:");

        lblCodigoPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Cédula del paciente:");

        txtCedulaPaciente.setBackground(new java.awt.Color(254, 254, 254));
        txtCedulaPaciente.setEnabled(false);
        txtCedulaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaPacienteKeyTyped(evt);
            }
        });

        btnRegistrarPaciente.setBackground(new java.awt.Color(75, 75, 253));
        btnRegistrarPaciente.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnRegistrarPaciente.setForeground(new java.awt.Color(254, 254, 254));
        btnRegistrarPaciente.setText("Registrar Paciente");
        btnRegistrarPaciente.setEnabled(false);
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });

        checkRegistro.setText("¿Está Registrado?");
        checkRegistro.setEnabled(false);
        checkRegistro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkRegistroStateChanged(evt);
            }
        });

        jLabel6.setText("Nombre del paciente:");

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Cita Médica");

        jLabel2.setText("Código de la cita:");

        txtAño.setBackground(new java.awt.Color(254, 254, 254));
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });

        txtMes.setBackground(new java.awt.Color(254, 254, 254));
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });

        txtDia.setBackground(new java.awt.Color(254, 254, 254));
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });

        jLabel11.setText("Día:");

        jLabel12.setText("Mes:");

        jLabel13.setText("Año:");

        btnHorasDisponibles.setBackground(new java.awt.Color(75, 75, 253));
        btnHorasDisponibles.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnHorasDisponibles.setForeground(new java.awt.Color(254, 254, 254));
        btnHorasDisponibles.setText("Horas Disponibles");
        btnHorasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorasDisponiblesActionPerformed(evt);
            }
        });

        jComboBox1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarPaciente)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(2, 2, 2)
                                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(1, 1, 1)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHorasDisponibles))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultarCodigo))
                            .addComponent(lblCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnGenerarCita)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtAño)
                    .addComponent(btnHorasDisponibles)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPaciente)
                    .addComponent(checkRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarCita)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        registrarPacienteForm registrarPacienteForm = new registrarPacienteForm();
        registrarPacienteForm.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void checkRegistroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkRegistroStateChanged
        if(checkRegistro.isSelected()){
            txtCedulaPaciente.setEnabled(true);
            btnConsultarCodigo.setEnabled(true);
            btnRegistrarPaciente.setEnabled(false);
        }else{
            txtCedulaPaciente.setEnabled(false);
            btnConsultarCodigo.setEnabled(false);
            btnRegistrarPaciente.setEnabled(true);
        }
    }//GEN-LAST:event_checkRegistroStateChanged

    private void btnConsultarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoActionPerformed
        String cedula = txtCedulaPaciente.getText();
        if(cedula.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo cédula del paciente está vacío", "Advertencia", 2);
            txtCedulaPaciente.setBackground(rojo);
        }else if (!esNumero(cedula)) {
            JOptionPane.showMessageDialog(rootPane, "La cédula del paciente no puede contener caracteres que no sean numéricos", "Error", 1);
            txtCedulaPaciente.setBackground(rojo);
        }else if (cedula.length() != 10){
            JOptionPane.showMessageDialog(rootPane, "La cédula del paciente solo puede tener 10 dígitos", "Advertencia", 2);
        }else{
            txtCedulaPaciente.setBackground(java.awt.Color.WHITE);
            try{
                callProcedureGetDatosPaciente(cedula);
            }catch (SQLException e) {
		System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConsultarCodigoActionPerformed

    private void btnGenerarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCitaActionPerformed
        String dato = lblNombrePaciente.getText();
        if(!dato.equals("")){
            try{
                callProcedureInsertarNuevaCita();
                JOptionPane.showMessageDialog(rootPane, "Registro exitoso", "Mensaje", 1);
            }catch (SQLException e) {
		System.out.println(e.getMessage());
            }
        }else
            JOptionPane.showMessageDialog(rootPane, "No se puede registrar", "Mensaje", 1);
    }//GEN-LAST:event_btnGenerarCitaActionPerformed

    private void btnHorasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorasDisponiblesActionPerformed
        String dia = txtDia.getText();
        String mes = txtMes.getText();
        String año = txtAño.getText();
        Calendar actual = Calendar.getInstance();
        int añoActual = actual.get(Calendar.YEAR);
        int diaActual = actual.get(Calendar.DAY_OF_MONTH);
        int mesActual = actual.get(Calendar.MONTH) + 1;
        String msg1 = "1", msg2 = "2", msg3 = "3"; //Cuando están vacíos es porque no hay ningún error en los datos
        String turnosNoDisponibles[] = new String[24];
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(false);

        if(dia.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo día está vacío", "Advertencia", 2);
            txtDia.setBackground(rojo);
            msg1 = "1";
        }else if(!esNumero(dia)){
            JOptionPane.showMessageDialog(rootPane, "El campo día solo está formado por números", "Advertencia", 2);
            txtDia.setBackground(rojo);
            msg1 = "1";
        }else if(Integer.parseInt(dia) < 0 || Integer.parseInt(dia) > 31){
            JOptionPane.showMessageDialog(rootPane, "Día Inválido: Solo puede tomar el valor de 1 - 31", "Advertencia", 2);
            txtDia.setBackground(rojo);
            msg1 = "1";
        }else{
            txtDia.setBackground(java.awt.Color.WHITE);
            msg1 = "";
        }

        if(!dia.equals("") && !mes.equals("") && !año.equals("") && esNumero(mes) && esNumero(año) && esNumero(dia) && (Integer.parseInt(mes)<12 && Integer.parseInt(mes)>0)){
            if(Integer.parseInt(año) == añoActual && Integer.parseInt(mes) == mesActual){
                if(Integer.parseInt(dia) < diaActual){
                    JOptionPane.showMessageDialog(rootPane, "Día inválido: Se ha escogido un día anterior al actual", "Advertencia", 2);
                    txtDia.setBackground(rojo);
                    msg1 = "1";
                }else{
                    txtDia.setBackground(java.awt.Color.WHITE);
                    msg1 = "";
                }
            }else if(Integer.parseInt(año) == añoActual && Integer.parseInt(mes) > mesActual){
                if(Integer.parseInt(dia) < 0 || Integer.parseInt(dia) > 31){
                    JOptionPane.showMessageDialog(rootPane, "Día Inválido: Solo puede tomar el valor de 1 - 31", "Advertencia", 2);
                    txtDia.setBackground(rojo);
                    msg1 = "1";
                }else{
                    txtDia.setBackground(java.awt.Color.WHITE);
                    msg1 = "";
                }
            }else if(Integer.parseInt(año) > añoActual){
                if(Integer.parseInt(dia) < 0 || Integer.parseInt(dia) > 31){
                    JOptionPane.showMessageDialog(rootPane, "Día Inválido: Solo puede tomar el valor de 1 - 31", "Advertencia", 2);
                    txtDia.setBackground(rojo);
                    msg1 = "1";
                }else{
                    txtDia.setBackground(java.awt.Color.WHITE);
                    msg1 = "";
                }
            }
        }

        if(mes.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo mes está vacío", "Advertencia", 2);
            txtMes.setBackground(rojo);
            msg2 = "2";
        }else if(!esNumero(mes)){
            JOptionPane.showMessageDialog(rootPane, "El campo mes solo está formado por números", "Advertencia", 2);
            txtMes.setBackground(rojo);
            msg2 = "2";
        }else if(Integer.parseInt(mes)<1 || Integer.parseInt(mes)>12){
            JOptionPane.showMessageDialog(rootPane, "Mes inválido: Solo puede tomar el valor de 1 - 12", "Advertencia", 2);
            txtMes.setBackground(rojo);
            msg2 = "2";
        }else{
            txtMes.setBackground(java.awt.Color.WHITE);
            msg2 = "";
        }

        if(!año.equals("") && !mes.equals("") && esNumero(año) && esNumero(mes) && (Integer.parseInt(mes)<12 && Integer.parseInt(mes)>0)){
            if(Integer.parseInt(año) == añoActual) {
                if(Integer.parseInt(mes) < mesActual){
                    JOptionPane.showMessageDialog(rootPane, "Mes inválido: Se ha escogido un mes anterior al actual", "Advertencia", 2);
                    txtMes.setBackground(rojo);
                    msg2 = "2";
                }else{
                    txtMes.setBackground(java.awt.Color.WHITE);
                    msg2 = "";
                }
            }else if(Integer.parseInt(año) > añoActual){
                if(Integer.parseInt(mes)<1 || Integer.parseInt(mes)>12){
                    JOptionPane.showMessageDialog(rootPane, "Mes inválido: Solo puede tomar el valor de 1 - 12", "Advertencia", 2);
                    txtMes.setBackground(rojo);
                    msg2 = "2";
                }else{
                    txtMes.setBackground(java.awt.Color.WHITE);
                    msg2 = "";
                }
            }
        }

        if(año.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo año está vacío", "Advertencia", 2);
            txtAño.setBackground(rojo);
            msg3 = "3";
        }else if(!esNumero(año)){
            JOptionPane.showMessageDialog(rootPane, "El campo año solo está formado por números", "Advertencia", 2);
            txtAño.setBackground(rojo);
            msg3 = "3";
        }else if(Integer.parseInt(año) < añoActual || Integer.parseInt(año) > añoActual+2){
            JOptionPane.showMessageDialog(rootPane, "Año inválido", "Advertencia", 2);
            txtAño.setBackground(rojo);
            msg3 = "3";
        } else{
            txtAño.setBackground(java.awt.Color.WHITE);
            msg3 = "";
        }

        if(msg1.equals("") && msg2.equals("") && msg3.equals("")){
            try{
                turnosNoDisponibles = callProcedureGetHorasReservadas(Integer.parseInt(dia), Integer.parseInt(mes), Integer.parseInt(año));
            }catch (SQLException e) {
		System.out.println(e.getMessage());
            }
            cargarHorasTurnoDisponiblesCombo(turnosNoDisponibles, Integer.parseInt(dia), Integer.parseInt(mes), Integer.parseInt(año));
            jComboBox1.setEnabled(true);
        }

    }//GEN-LAST:event_btnHorasDisponiblesActionPerformed

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        if(txtDia.getText().length()>1)
        evt.consume();
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        if(txtMes.getText().length()>1)
        evt.consume();
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
       if(txtAño.getText().length()>3)
        evt.consume();
    }//GEN-LAST:event_txtAñoKeyTyped

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        if(jComboBox1.isEnabled()){
            checkRegistro.setEnabled(true);
        }else{
            checkRegistro.setEnabled(false);
            btnRegistrarPaciente.setEnabled(false);
        }
        if(!(lblCodigoPaciente.getText().equals("")))
            btnGenerarCita.setEnabled(true);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void txtCedulaPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaPacienteKeyTyped
        if(txtCedulaPaciente.getText().length()>9)
        evt.consume();
    }//GEN-LAST:event_txtCedulaPacienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevaCitaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevaCitaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevaCitaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevaCitaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    nuevaCitaForm nueva = new nuevaCitaForm();
                    nueva.setVisible(true);
                    try {
			nueva.callProcedureGetIDCita();
                    }catch (SQLException e) {
			System.out.println(e.getMessage());
                    }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCodigo;
    private javax.swing.JButton btnGenerarCita;
    private javax.swing.JButton btnHorasDisponibles;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JCheckBox checkRegistro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoPaciente;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedulaPaciente;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables

    public boolean esNumero(String str) {
        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

    private void callProcedureGetIDCita() throws SQLException {
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String obtenerCitaMaxima = "{call obtenerCitaMaxima(?)}";
        try {
                dbConnection = conexiondb.getDBConnection();
                callableStatement = dbConnection.prepareCall(obtenerCitaMaxima);
                callableStatement.registerOutParameter(1, java.sql.Types.INTEGER);
                //MariaDB
                callableStatement.executeUpdate();// execute obtenerCitaMaxima store procedure
                //MySQL
                //callableStatement.executeQuery();// execute obtenerCitaMaxima store procedure
                int maxcita = callableStatement.getInt(1);
                lblCodigo.setText(String.valueOf(maxcita+1));
        } catch (SQLException e) {
                System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
    }

    private String[] callProcedureGetHorasReservadas(int dia, int mes, int año) throws SQLException{
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String filtrarCitaFecha = "{call filtrarCitaFecha(?)}";
        ResultSet rs;
        String result[] = new String[24];
        int fila=0;
        try{
            dbConnection = conexiondb.getDBConnection();
            Calendar c = Calendar.getInstance();
            c.set(año, mes-1, dia);
            java.sql.Date sqlDate = new java.sql.Date(c.getTimeInMillis());
            sqlDate.toLocalDate();
            //System.out.println("utilDate:" + c);
            //System.out.println("sqlDate:" + sqlDate);
            //System.out.println("Date:" + sqlDate.toLocalDate());
            callableStatement = dbConnection.prepareCall(filtrarCitaFecha, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            callableStatement.setDate(1, sqlDate);
            rs = callableStatement.executeQuery();
            while(rs.next()){
                result[fila]=rs.getString(4);//Turno
                //result[fila+1][columna]=rs.getString(3);//Hora
                fila++;
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
        return result;
    }

    public Date callProcedureGetFechaServidor() throws SQLException{
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String fechaActual = "{call fechaActual(?)}";
        Date fa = new Date();
        try {
                dbConnection = conexiondb.getDBConnection();
                callableStatement = dbConnection.prepareCall(fechaActual);
                callableStatement.registerOutParameter(1, java.sql.Types.DATE);
                //MariaDB
                callableStatement.executeUpdate();// execute obtenerCitaMaxima store procedure
                //MySQL
                //callableStatement.executeQuery();// execute obtenerCitaMaxima store procedure
                fa = callableStatement.getDate(1);
                //System.out.println("Fecha actual del servidor: " + fa);
        } catch (SQLException e) {
                System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
        return fa;
    }

    private void cargarHorasTurnoDisponiblesCombo(String arrayturno[], int dia, int mes, int año){
        int fila, turno, noEstaDisponible, turnoinicial = 1;
        String turnoHora;
        Date da = new Date();
        try {
            da = callProcedureGetFechaServidor();
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        GregorianCalendar gc = new GregorianCalendar(año, mes-1, dia);
        Date d = gc.getTime();
        if(d.compareTo(da) == 0){
            if(arrayturno[0] != null)
                turnoinicial = Integer.parseInt(arrayturno[0]);
            else{
                try{
                    turnoinicial = callProcedureGetTurnoMaximoFecha() + 1;
                }catch(SQLException e){
                    System.out.println(e.getMessage());
                }

            }
        }else
            turnoinicial = 1;

        for(turno = turnoinicial; turno < 25; turno++){
            noEstaDisponible = 0;
            fila=0;
            while(arrayturno[fila] != null){
                if(Integer.parseInt(arrayturno[fila]) == turno)
                    noEstaDisponible++;
                fila++;
            }
            if(noEstaDisponible == 0){
                turnoHora = turno + " / " + getHoraTurno(turno);
                jComboBox1.addItem(turnoHora);
            }
        }


    }

    private String getHoraTurno(int turno){
        String horat = "08:00:00 AM";
        switch(turno){
            case 1:
                horat = "08:00:00 AM";
                break;
            case 2:
                horat = "08:15:00 AM";
                break;
            case 3:
                horat = "08:30:00 AM";
                break;
            case 4:
                horat = "08:45:00 AM";
                break;
            case 5:
                horat = "09:00:00 AM";
                break;
            case 6:
                horat = "09:15:00 AM";
                break;
            case 7:
                horat = "09:30:00 AM";
                break;
            case 8:
                horat = "09:45:00 AM";
                break;
            case 9:
                horat = "10:00:00 AM";
                break;
            case 10:
                horat = "10:15:00 AM";
                break;
            case 11:
                horat = "10:30:00 AM";
                break;
            case 12:
                horat = "10:45:00 AM";
                break;
            case 13:
                horat = "11:00:00 AM";
                break;
            case 14:
                horat = "11:15:00 AM";
                break;
            case 15:
                horat = "11:30:00 AM";
                break;
            case 16:
                horat = "11:45:00 AM";
                break;
            case 17:
                horat = "12:00:00 PM";
                break;
            case 18:
                horat = "12:15:00 PM";
                break;
            case 19:
                horat = "12:30:00 PM";
                break;
            case 20:
                horat = "12:45:00 PM";
                break;
            case 21:
                horat = "02:00:00 PM";
                break;
            case 22:
                horat = "02:15:00 PM";
                break;
            case 23:
                horat = "02:30:00 PM";
                break;
            case 24:
                horat = "02:45:00 PM";
                break;
        }
        return horat;
    }

    private int callProcedureGetTurnoMaximoFecha() throws SQLException {
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String turnoMaximoFechaActual = "{call turnoMaximoFechaActual(?)}";
        int maxturno = 1;
        try {
                dbConnection = conexiondb.getDBConnection();
                callableStatement = dbConnection.prepareCall(turnoMaximoFechaActual);
                callableStatement.registerOutParameter(1, java.sql.Types.INTEGER);
                //MariaDB
                callableStatement.executeUpdate();// execute turnoMaximoFechaActual store procedure
                //MySQL
                //callableStatement.executeQuery();// execute turnoMaximoFechaActual store procedure
                maxturno = callableStatement.getInt(1);
        } catch (SQLException e) {
                System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
        return maxturno;
    }

    private void callProcedureGetDatosPaciente(String cedula) throws SQLException {
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String getDatosPaciente = "{call getDatosPaciente(?)}";
        ResultSet rs;
        try {
                dbConnection = conexiondb.getDBConnection();
                callableStatement = dbConnection.prepareCall(getDatosPaciente, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                callableStatement.setString(1, cedula);
                //MariaDB
                rs = callableStatement.executeQuery();// execute turnoMaximoFechaActual store procedure
                //MySQL
                //callableStatement.executeQuery();// execute turnoMaximoFechaActual store procedure
                if(rs.next()){
                    String str1 = rs.getString(3);
                    String str2 = rs.getString(4);
                    lblNombrePaciente.setText(rs.getString(3) + " " + rs.getString(4));
                    lblCodigoPaciente.setText(rs.getString(1));
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se encontró al paciente con la cédula " + cedula);
                    lblNombrePaciente.setText("");
                    lblCodigoPaciente.setText("");
                }
        } catch (SQLException e) {
                System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
    }

    private void callProcedureInsertarNuevaCita() throws SQLException{
        Connection dbConnection = null;
        CallableStatement callableStatement = null;
        String insertarNuevaCita = "{call insertarNuevaCita(?,?,?,?,?)}";
        int turno = getTurnoCombo(jComboBox1.getSelectedItem().toString());
        String strHora = getHoraTurno(turno);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        Date dt;
        long ms = Integer.toUnsignedLong(0);
        try{
            ms = sdf.parse(strHora).getTime();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        Calendar c = Calendar.getInstance();
        c.set(Integer.parseInt(txtAño.getText()), Integer.parseInt(txtMes.getText())-1, Integer.parseInt(txtDia.getText()));
        java.sql.Date sqlDate = new java.sql.Date(c.getTimeInMillis());
        sqlDate.toLocalDate();
        java.sql.Time sqlTime = new java.sql.Time(ms);

        //System.out.println("utilDate:" + c);
        //System.out.println("sqlDate:" + sqlDate);
        //System.out.println("Date:" + sqlDate.toLocalDate());
        //System.out.println("Hora: " + sqlTime);


        try{
            dbConnection = conexiondb.getDBConnection();
            callableStatement = dbConnection.prepareCall(insertarNuevaCita);
            callableStatement.setDate(1, sqlDate);
            callableStatement.setInt(3, turno);
            callableStatement.setInt(4, Integer.parseInt(lblCodigoPaciente.getText()));
            callableStatement.setInt(5, 0);
            callableStatement.setTime(2, sqlTime);
            callableStatement.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
                if (callableStatement != null)
                        callableStatement.close();
                if (dbConnection != null)
                        dbConnection.close();
        }
    }

    private int getTurnoCombo(String str){
        int indexend=0;
        for(int i=0; i<str.length(); i++){
            if(str.charAt(i) == '/')
                i=str.length();
            else
                indexend++;
        }
        return Integer.parseInt(str.substring(0, indexend-1));
    }
}
