/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesoPacket;

import principalPacket.pantallaPrincipalForm;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Properties;

//===
import java.sql.*;
import conexiondb.*;

/**
 *
 * @author j3s
 */
public class accesoForm extends javax.swing.JFrame {



    /**
     * Creates new form accesoForm
     */
    public accesoForm() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        lblContraseña.setText("Contraseña:");

        lblUsuario.setText("Usuario:");

        txtUsuario.setBackground(new java.awt.Color(254, 254, 254));

        txtContraseña.setBackground(new java.awt.Color(254, 254, 254));

        btnIngresar.setBackground(new java.awt.Color(75, 75, 253));
        btnIngresar.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 13)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(254, 254, 254));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 24)); // NOI18N
        jLabel1.setText("Ingreso al sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsuario)
                                .addComponent(lblContraseña))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsuario)
                                .addComponent(txtContraseña)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnIngresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText();
        String contrasena = txtContraseña.getText();
//===
//        this.sql = "SELECT usuario FROM acceso WHERE usuario = "+"\'"+usuario +"\'"+";";
       // this.sql = "SELECT id_acceso FROM acceso WHERE usuario = "+"\'"+usuario +"\'"+" and contrasena = SHA1("+"\'"+contrasena +"\'"+");";
        //String sql2 = "select id_acceso from acceso where contrasena = SHA1(\'"+contrasena +"\')";


        if(usuario.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo del usuario está vacío", "Advertencia", 2);
            txtUsuario.setBackground(java.awt.Color.YELLOW);
//        }else if(!(usuario.equals("medico") || usuario.equals("asistente"))){
//            JOptionPane.showMessageDialog(rootPane, "El usuario no existe", "Error", 3);
//            txtUsuario.setBackground(java.awt.Color.PINK);
        }else
            txtUsuario.setBackground(java.awt.Color.WHITE);

        if(contrasena.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo de la contraseña está vacío", "Advertencia", 2);
            txtContraseña.setBackground(java.awt.Color.YELLOW);
//===
//        }else if(!contrasena.equals("1234")){
//            JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Error", 3);
//            txtContraseña.setBackground(java.awt.Color.PINK);
        }else
            txtContraseña.setBackground(java.awt.Color.WHITE);

//===
//        if(consultar(sql,c)){
//		if(consultar(usuario,contrasena,c)){
		if(consultar(usuario,contrasena)){
            pantallaPrincipalForm pantallaPrincipalForm = new pantallaPrincipalForm();
            this.setVisible(false);
            pantallaPrincipalForm.setVisible(true);

        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado", "Advertencia", 2);
        }


//        if(((usuario.equals("medico") || usuario.equals("asistente")))&&(contrasena.equals("1234")))
//        {
//            pantallaPrincipalForm pantallaPrincipalForm = new pantallaPrincipalForm();
//            this.setVisible(false);
//            pantallaPrincipalForm.setVisible(true);
//        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accesoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accesoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accesoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accesoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>




        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               accesoForm f = new accesoForm();
               f.setVisible(true);
               f.c = f.Connection();
            }
        });
    }
public String sql;
Statement st;
public Connection c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

public  Connection Connection() {
    try{
    String dbClassName = "com.mysql.jdbc.Driver";
    String CONNECTION =
                          "jdbc:mysql://127.0.0.1/sistema_medico";
        System.out.println(dbClassName);
    // Class.forName(xxx) loads the jdbc classes and
    // creates a drivermanager class factory
    Class.forName(dbClassName);

    // Properties for user and password.
    Properties p = new Properties();
    p.put("user","root");
    //===
//    p.put("password","1359sss");
	    p.put("password","123");

    // Now try to connect
    Connection c = DriverManager.getConnection(CONNECTION,p);
    System.out.println("It works !");
    return c;
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane,"No se pudo conectar a la base de datos");
        e.printStackTrace();
    }
    return null;
}

public boolean consultar (String sql,Connection c)
{
    try{
    this.st = c.createStatement();
    ResultSet rs = st.executeQuery(sql);
    rs.next();
    String user = rs.getString("usuario");
    System.out.println("It works 2");
    st.close();
    System.out.println("Se cerro");
    return true;
    }catch(Exception e){

    }
    try{
    st.close();
    System.out.println("Se cerro");
    }catch(Exception r){

    }

    return false;
}

//===
//public boolean consultar (String usuario, String contrasena, Connection c)
public boolean consultar (String usuario, String contrasena)
{
	int valor = 0;
	boolean valido = false;

	try{
	c = conexiondb.getDBConnection();
	CallableStatement proc = c.prepareCall("{ call sistema_medico.validar_acceso(?,?,?) }");
	proc.setString(1, usuario);
	proc.setString(2, contrasena);
	//proc.registerOutParameter(3, java.sql.Types.INTEGER, valor);
	proc.registerOutParameter(3, java.sql.Types.INTEGER);
	proc.execute();
	valor = proc.getInt(3);
	proc.close();

	}catch(Exception e){
		e.printStackTrace();
	}

	valido = (valor==1);
	return valido;
}

}
